# 以下为阈值 1个h表示一级阈值，2个h为二级
sensors_threshold: # 判断单个炮数据是否超出阈值
  sensor1:
    of_h_r: '0.0'
    of_hh_r: '0.02013168'
    of_h_z: '0.00933888'
    of_hh_z: '1.0'
  sensor2:
    of_h_r: '0.01137486'
    of_hh_r: '0.01202064'
    of_h_z: '0.00645622'
    of_hh_z: '0.00664306'
  sensor3:
    of_h_r: '0.0'
    of_hh_r: '0.0'
    of_h_z: '0.0'
    of_hh_z: '0.0'
  sensor4:
    of_h_r: '0.0'
    of_hh_r: '0.0'
    of_h_z: '0.0'
    of_hh_z: '0.0'
  sensor5:
    of_h_r: '0.0116545'
    of_hh_r: '0.01250253'
    of_h_z: '0.02849718'
    of_hh_z: '0.02902619'
  sensor6:
    of_h_r: '0.0'
    of_hh_r: '0.0'
    of_h_z: '0.0'
    of_hh_z: '0.0'
