save_plot_folder: basic_plot # 图片的保存文件夹
plots:
#  sensor1
  - name: "sensor1" # name show as plot tile
    plot_source: "sensor1/$shot_0$.hdf5" # hdf file path below data source
    plot_channel: "channel0"
    line_color: "red"
    enable_detail: true
    x_max: 4
    x_min: 3.5
    y_max: "-"
    y_min: "-"
    x_label: "时间 [s]"
    y_label: "加速度 [g]"
    title: "x轴方向"
    output: "sensor1x.png" # output file name and path under the output folder
    drop_last: true # drop last point for vibration sensor which is the temp
  - name: "sensor1"
    plot_source: "sensor1/$shot_0$.hdf5"
    plot_channel: "channel1"
    line_color: "red"
    enable_detail: true
    x_max: 4
    x_min: 3.5
    y_max: "-"
    y_min: "-"
    x_label: "时间 [s]"
    y_label: "加速度 [g]"
    title: "y轴方向"
    output: "sensor1y.png"
    drop_last: true
  - name: "sensor1"
    plot_source: "sensor1/$shot_0$.hdf5"
    plot_channel: "channel2"
    line_color: "red"
    enable_detail: true
    x_max: 4
    x_min: 3.5
    y_max: "-"
    y_min: "-"
    x_label: "时间 [s]"
    y_label: "加速度 [g]"
    title: "z轴方向"
    output: "sensor1z.png"
    drop_last: true
#  sensor2
  - name: "sensor2"
    plot_source: "sensor2/$shot_0$.hdf5"
    plot_channel: "channel0"
    line_color: "red"
    enable_detail: true
    x_max: 4
    x_min: 3.5
    y_max: "-"
    y_min: "-"
    x_label: "时间 [s]"
    y_label: "加速度 [g]"
    title: "x轴方向"
    output: "sensor2x.png"
    drop_last: true
  - name: "sensor2"
    plot_source: "sensor2/$shot_0$.hdf5"
    plot_channel: "channel1"
    line_color: "red"
    enable_detail: true
    x_max: 4
    x_min: 3.5
    y_max: "-"
    y_min: "-"
    x_label: "时间 [s]"
    y_label: "加速度 [g]"
    title: "y轴方向"
    output: "sensor2y.png"
    drop_last: true
  - name: "sensor2"
    plot_source: "sensor2/$shot_0$.hdf5"
    plot_channel: "channel2"
    line_color: "red"
    enable_detail: true
    x_max: 4
    x_min: 3.5
    y_max: "-"
    y_min: "-"
    x_label: "时间 [s]"
    y_label: "加速度 [g]"
    title: "z轴方向"
    output: "sensor2z.png"
    drop_last: true
#  sensor3
  - name: "sensor3"
    plot_source: "sensor3/$shot_0$.hdf5"
    plot_channel: "channel0"
    line_color: "red"
    enable_detail: true
    x_max: 4
    x_min: 3.5
    y_max: "-"
    y_min: "-"
    x_label: "时间 [s]"
    y_label: "加速度 [g]"
    title: "x轴方向"
    output: "sensor3x.png"
    drop_last: true
  - name: "sensor3"
    plot_source: "sensor3/$shot_0$.hdf5"
    plot_channel: "channel1"
    line_color: "red"
    enable_detail: true
    x_max: 4
    x_min: 3.5
    y_max: "-"
    y_min: "-"
    x_label: "时间 [s]"
    y_label: "加速度 [g]"
    title: "y轴方向"
    output: "sensor3y.png"
    drop_last: true
  - name: "sensor3"
    plot_source: "sensor3/$shot_0$.hdf5"
    plot_channel: "channel2"
    line_color: "red"
    enable_detail: true
    x_max: 4
    x_min: 3.5
    y_max: "-"
    y_min: "-"
    x_label: "时间 [s]"
    y_label: "加速度 [g]"
    title: "z轴方向"
    output: "sensor3z.png"
    drop_last: true
#  sensor4
  - name: "sensor4"
    plot_source: "sensor4/$shot_0$.hdf5"
    plot_channel: "channel0"
    line_color: "red"
    enable_detail: true
    x_max: 4
    x_min: 3.5
    y_max: "-"
    y_min: "-"
    x_label: "时间 [s]"
    y_label: "加速度 [g]"
    title: "x轴方向"
    output: "sensor4x.png"
    drop_last: true
  - name: "sensor4"
    plot_source: "sensor4/$shot_0$.hdf5"
    plot_channel: "channel1"
    line_color: "red"
    enable_detail: true
    x_max: 4
    x_min: 3.5
    y_max: "-"
    y_min: "-"
    x_label: "时间 [s]"
    y_label: "加速度 [g]"
    title: "y轴方向"
    output: "sensor4y.png"
    drop_last: true
  - name: "sensor4"
    plot_source: "sensor4/$shot_0$.hdf5"
    plot_channel: "channel2"
    line_color: "red"
    enable_detail: true
    x_max: 4
    x_min: 3.5
    y_max: "-"
    y_min: "-"
    x_label: "时间 [s]"
    y_label: "加速度 [g]"
    title: "z轴方向"
    output: "sensor4z.png"
    drop_last: true
#  sensor5
  - name: "sensor5"
    plot_source: "sensor5/$shot_0$.hdf5"
    plot_channel: "channel0"
    line_color: "red"
    enable_detail: true
    x_max: 4
    x_min: 3.5
    y_max: "-"
    y_min: "-"
    x_label: "时间 [s]"
    y_label: "加速度 [g]"
    title: "x轴方向"
    output: "sensor5x.png"
    drop_last: true
  - name: "sensor5"
    plot_source: "sensor5/$shot_0$.hdf5"
    plot_channel: "channel1"
    line_color: "red"
    enable_detail: true
    x_max: 4
    x_min: 3.5
    y_max: "-"
    y_min: "-"
    x_label: "时间 [s]"
    y_label: "加速度 [g]"
    title: "y轴方向"
    output: "sensor5y.png"
    drop_last: true
  - name: "sensor5"
    plot_source: "sensor5/$shot_0$.hdf5"
    plot_channel: "channel2"
    line_color: "red"
    enable_detail: true
    x_max: 4
    x_min: 3.5
    y_max: "-"
    y_min: "-"
    x_label: "时间 [s]"
    y_label: "加速度 [g]"
    title: "z轴方向"
    output: "sensor5z.png"
    drop_last: true
#  sensor6
  - name: "sensor6"
    plot_source: "sensor6/$shot_0$.hdf5"
    plot_channel: "channel0"
    line_color: "red"
    enable_detail: true
    x_max: 4
    x_min: 3.5
    y_max: "-"
    y_min: "-"
    x_label: "时间 [s]"
    y_label: "加速度 [g]"
    title: "x轴方向"
    output: "sensor6x.png"
    drop_last: true
  - name: "sensor6"
    plot_source: "sensor6/$shot_0$.hdf5"
    plot_channel: "channel1"
    line_color: "red"
    enable_detail: true
    x_max: 4
    x_min: 3.5
    y_max: "-"
    y_min: "-"
    x_label: "时间 [s]"
    y_label: "加速度 [g]"
    title: "y轴方向"
    output: "sensor6y.png"
    drop_last: true
  - name: "sensor6"
    plot_source: "sensor6/$shot_0$.hdf5"
    plot_channel: "channel2"
    line_color: "red"
    enable_detail: true
    x_max: 4
    x_min: 3.5
    y_max: "-"
    y_min: "-"
    x_label: "时间 [s]"
    y_label: "加速度 [g]"
    title: "z轴方向"
    output: "sensor6z.png"
    drop_last: true