data_source: D:/study/mpm/data2/$shot_2$00/$shot$.hdf5 # 数据地址
Inference_path: D:/study/mpm/results/result2/$shot_2$00/$shot$ # 输出地址
#threshold_config_path: D:/资源汇总/新球磨项目/configs/threshold_configs/$bm$/rms_threshold_config.yml
plot_config_path: D:/资源汇总/新球磨项目/configs/plot_configs/basic_plot_config/basic_plot_config.yml
plot_desc_path: D:/资源汇总/新球磨项目/configs/plot_configs/basic_plot_config/basic_plot_desc.yml
plot_desc_file: plot_desc.yml # 复制的画图配置文件的名称
summary_path: D:/资源汇总/新球磨项目/Data/Inference/$bm$ # 公共文件路径
is_training: False # 是否自动更新警报阈值
is_running_update: False # 是否更新判断是否运行的阈值
rms_image_path: D:/资源汇总/新球磨项目/Data/Inference/$bm$/rms_image # 历史RMS画图，辅助验证确定is_running阈值是否正确
training_shots: 5000

db: # 数据库的连接信息
  connection: mongodb://localhost:27017/
  db_name: mpm
  collection: rms

tags:
  - \VibTF_4R
  - \VibTF_4phi
  - \VibTF_4Z
  - \VibTF_11R
  - \VibTF_11phi
  - \VibTF_11Z
  - \VibTF_7R
  - \VibTF_14R
  - \VibTF_9R
  - \VibV_5R
  - \VibV_5phiZ
  - \VibV_12R
  - \VibV_12phiZ
  - \VibV_7R
  - \VibV_9R
  - \VibV_14Ks

#- '\\VibTF_4R'
#- '\\VibTF_4phi'
#- '\\VibTF_4Z'
#- '\\VibTF_11R'
#- '\\VibTF_11phi'
#- '\\VibTF_11Z'
#- '\\VibTF_7R'
#- '\\VibTF_14R'
#- '\\VibTF_9R'
#- '\\VibV_5R'
#- '\\VibV_5phiZ'
#- '\\VibV_12R'
#- '\\VibV_12phiZ'
#- '\\VibV_7R'
#- '\\VibV_9R'
#- '\\VibV_14Ks'



